### ISSUE TITLE
Mixing ratios don't always add up to 1

### ISSUE THREAD

**Issue by MFTondreau** [FormingWorlds/JANUS#1]
In the case where all chemical species condense at the top of the atmosphere (when the dry_list is empty), the mixing ratios don't add up to 1 anymore.

**Comment by timlichtenberg** [comment]
Ok, this then seems more of a new feature development than a bug, there are of course limits to the adiabatic assumption inherent to JANUS. Please suggest to @MFTondreau to make use of / contribute to JANUS instead of a offline detached version that is probably out of date. :)
