### ISSUE TITLE
Make Janus a PyPI package

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/JANUS#15]
We would like to make JANUS a PyPI package to ease its integration into PROTEUS.

**Comment by nichollsh** [comment]
For JANUS to be made a PyPI package, it needs to be able to automatically compile SOCRATES. 

For AGNI, which also uses SOCRATES, I've tried to make this a bit easier by adding a `configure` script. See files in this folder: https://github.com/nichollsh/AGNI/tree/main/socrates. The configure script generates a Mk_cmd file automatically, by locating the NetCDF libraries and adjusting things for your platform. 

Maybe this is useful for JANUS.
