### ISSUE TITLE
Publish workflow breaks because master branch is protected

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/JANUS#28]
In the publish workflow we push an update of the requirement file and update of the version number in any relevant file. But it breaks because master branch is protected.

It seems there is no way to bypass the master branch protection within Github actions. Maybe push instead into a release branch and/or automatically create pull request?

Once this is solved, we should do the same for the mors package.

**Comment by stefsmeets** [comment]
Is it also an option to turn off branch protection? Why do we want branch protection here?

**Comment by stefsmeets** [comment]
Okay, just seems overly complicated to me. Branch protection just gets in the way and we are just a few working on this code, so we don't get the benefits, only the complications 😅

**Comment by timlichtenberg** [comment]
If there is an option to keep up master branch protection for now I'd appreciate that. But perhaps there is a different way to set this up? We need to ensure that only reviewed PRs can get pulled into master, and only by a select group of people. This is simply, because it has proven wise to keep this up in the past. :)

**Comment by stefsmeets** [comment]
I see three options:
1. No branch protection. Workflow works as advertised.
2. Use a release branch. Tricky to set up, now you have to manage 2 branches. And the release branch is not protected if we want to use this workflow, so whatever you are protecting the main branch still from has free reign on the release branch.
3. Keep branch protection and don't use this workflow. Do semi-manual releases. No big deal, needs to be done from the command line and takes a few min. It's mostly about bumping the version. It's somewhat error-prone (I talk from experience 😁)

In the end I believe with branch protection you are trying to solve a social problem by setting arbitrary technical limitations. You can already do quite a bit by choosing who has read/write access to this repo.

My vote is on 1, but 3 is fine too (If whoever does the releases agrees). If we go for 3 I will open a PR to remove the workflow and write up the steps to follow.

**Comment by stefsmeets** [comment]
@timlichtenberg Let's go for 3, let me know if you disagree. I will write up a bit of documentation with the steps to take to make a release.

**Comment by timlichtenberg** [comment]
Can you maybe clarify for me, we are talking about pypi releases, right?

**Comment by timlichtenberg** [comment]
OK, yes, then let's do 3 for now.
