### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/JANUS#29]
Create a read the docs page to:
- give installation instructions
- show basic usage/worksflow
- list config file options

Also we could turn the scripts in the example folder into notebooks.

**Comment by stefsmeets** [comment]
It would be nice to use mkdocs for the documentation: https://www.mkdocs.org/
It's markdown based and compatible with readthedocs.

**Comment by nichollsh** [comment]
Using Mkdocs sounds great. I personally find restructuredtext quite confusing compared to markdown.

**Comment by timlichtenberg** [comment]
I agree, I am also a bit unhappy how convoluted it currently is to edit the Docs. Where would this be hosted?

**Comment by nichollsh** [comment]
Maybe @stefsmeets can provide more info, but there's[ details on the MkDocs page](https://www.mkdocs.org/user-guide/deploying-your-docs/) describing how to deploy it to GitHub pages. So I think that it would be hosted at something like: https://FormingWorlds.github.io/JANUS/

This is also how AGNI hosts its wiki.

**Comment by timlichtenberg** [comment]
Which one do you favour...? :>

**Comment by stefsmeets** [comment]
Oops, readthedocs 🚀
