### ISSUE TITLE
Use standard directory for data

### ISSUE THREAD

**Issue by stefsmeets** [FormingWorlds/JANUS#36]
The code requires the user to specify a default directory to store the data. This is somewhat annoying, and it would be nice if we could use a default directory. I have had good experiences with `platformdirs`, which works cross-platform and provides a default location based on common standards.

I propose to use `user_data_dir('JANUS')` or `user_data_dir('PROTEUS')` if we must have something for the across all the proteus/fwl projects.

**Comment by nichollsh** [comment]
How does this work if the user wishes to store the data on a different file system? For example, on a networked file system different to the one containing the user's home directory.

**Comment by stefsmeets** [comment]
It respects the XDG convention: https://specifications.freedesktop.org/basedir-spec/latest/

This means that setting `XDG_DATA_HOME` can be used to change the directory. This can be set up by a system administrator or the user.

**Comment by nichollsh** [comment]
Ah, I see, so we could have both functionalities present. Makes sense to me, especially if a user doesn't want to modify their environment.
