### ISSUE TITLE
Inconsistent SOCRATES environment variables

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/JANUS#51]
The new method for accessing the SOCRATES directory defaults to the `SOCRATES` env variable. If this is unset, then it uses the directory provided by `platformdirs`.

However, using `SOCRATES` is inconsistent with other codes, which instead use the variable name `RAD_DIR`. This includes SOCRATES itself, AGNI, and PROTEUS. We should decide which is going to be used going forward.

@stefsmeets what do you think?

**Comment by stefsmeets** [comment]
I'm all for consistency, so if it makes more sense to have to `RAD_DIR`, we should change it.
