### ISSUE TITLE
Large git folder when cloned

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/JANUS#58]
Cloning JANUS can be relatively slow despite the codebase now mostly containing code, with minimal amounts of other files. The total size on disk is about 189 MB, however, most of this is actually from the `.git` folder itself.

```
101K	./tools
130K	./src/janus/data
232K	./src/janus/utils
430K	./src/janus
434K	./src
188M	./.git/objects/pack/pack-ef89b4859cb0123c8f9d93186403ac7c9379552a.pack
189M	./.git
189M	./.git/objects
189M	./.git/objects/pack
189M	.
```

I assume this is because there's information left about previous revisions, when we were still packaging large files. We could consider reducing this folder size, but I am unsure how that would be done.

@stefsmeets or @lsoucasse ?

**Comment by lsoucasse** [comment]
Indeed, the git history of the large files is still there. We need to somewhat to erase these files there. I have spotted [this](https://www.geeksforgeeks.org/how-to-remove-a-large-file-from-commit-history-in-git/) on the web which seems to solve such issue.

**Comment by nichollsh** [comment]
There's a nice post on this thread about listing large files in the history.
https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history

**Comment by nichollsh** [comment]
And also: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by nichollsh** [comment]
The repos can be fully backed up this way:
https://stackoverflow.com/a/54040382

The most precise way to do remove the large files is with this solution:
https://stackoverflow.com/a/61602985

The analyse command produces a list of large directories (to be removed). The filter-repo command then removes these directories from the history, as required.

The new history can then be pushed to the remote with `git push --mirror`. However, this seems to neglect pull requests because they are a GitHub thing, not a Git thing. To be safe, we should probably do this on a copy of the repositories.

**Comment by nichollsh** [comment]
See also instructions on GitHub: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

**Comment by lsoucasse** [comment]
I have tested the following commands in my [fork](https://github.com/lsoucasse/JANUS) of Janus.
`git filter-repo --path dir_to_delete --invert-paths`
`git remote add origin git@github.com:lsoucasse/JANUS.git`
`git push --set-upstream origin main --force`

It reduces the size from 190M to 2M. If you are happy with it I can make the same here. I think it is safe as we have the git archive of Janus, as well as all the spectral files in the OSF.

**Comment by nichollsh** [comment]
Oh wow - very nice. This seems to have preserved this history nicely, although the commit hashes have changed. With the backups I think it should be fine. 

We could copy your fork back to `FormingWorlds/JANUS` (making it standalone, not a fork of `lsoucasse/JANUS`)?

Might make sense to rename the current JANUS to `FormingWorlds/JANUS_OLD` or something?

**Comment by nichollsh** [comment]
Also, is this fork an up-to-date version of JANUS?

**Comment by lsoucasse** [comment]
Oh, I thought I will just do the same operations directly on the Forming World repo. My fork was just for testing purposes. I don't think we need a `JANUS_OLD` since we have the archive on the OSF.

**Comment by nichollsh** [comment]
Fair enough - seems like it should be okay, and I agree we have the backup. Will this preserve the issues and the releases?

**Comment by lsoucasse** [comment]
You cannot avoid rewritting the commit hashes. The tags need to be reset to the new corresponding commits. I will make an archive with the current state of Janus before applying the changes.

**Comment by lsoucasse** [comment]
Done! Closing this issue.

The Janus archive with full history up to 24.09.12 can be found [here](https://osf.io/8w9tm/).

**Comment by nichollsh** [comment]
Thanks Laurent! Nice work. Seems like GitHub still stores the old commit hashes anyway, so we can access them if necessary.

Old: https://github.com/FormingWorlds/JANUS/commit/1fd17a8350515d9d03af30155b9e19a94f1a8e21
New: https://github.com/FormingWorlds/JANUS/commit/8ae28b133ec0f8139bef28c183c8ca24f4a9b257
