### ISSUE TITLE
Introduce convective inhibition in JANUS

### ISSUE THREAD

**Issue by timlichtenberg** [FormingWorlds/JANUS#6]
- [ ] Include convective inhibition criterion in the dry adjustment scheme
- [ ] Introduce moist convection in adjustment

Speed up time stepping via either:
- [ ] Method 1: calling entire fortran code from AEOLUS (may require lots of work on the fortran side to generalise to multi-component atmospheres)
- [ ] Method 2: wrapping the fortran call to SOCRATES in a python script (involves less intrusion on main AEOLUS code, but may be slower depending on what is the time-limiting step)

**Comment by timlichtenberg** [comment]
Is this still reasonable to do or should we focus on developing this in AGNI? @hinnes97 @nichollsh

**Comment by nichollsh** [comment]
I think that we should do this in AGNI. However, it might be useful to have it in both? I don't know how much work it would take to implement it inside JANUS.

**Comment by hinnes97** [comment]
Hi! Sorry for missing this -  I think AGNI makes more sense, since we can actually self consistently solve for the radiative gradient in the inhibited layers. I don't know if this is possible in JANUS?

**Comment by timlichtenberg** [comment]
Superseded by AGNI developments.
